sillsdev/silnlp

silnlp/nmt/experiment.py

I've added command line arguments for --preprocess --train and --test.  If none are specified all three actions occur as expected. If  one or more are specified only those actions are performed.

Add cli arguments for preprocess train and test.

---

silnlp/common/utils.py
silnlp/nmt/experiment.py
silnlp/nmt/translate.py

Updated so that the code formats the data more clearly and reuses the same functions.
The functions were placed in the common.utils.py file.
TO DO:
Add similar reporting to the preprocess, train and test scripts maybe.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/161)

Debug experiments paths

---

silnlp/nmt/config.py
silnlp/nmt/hugging_face_config.py

When I refactored the tokenizer code during the previous request, there was an unintended consequence where inferencing would unsuccessfully try to update the tokenizer even though the tokenizer had already been updated during preprocessing. This update adds an optional argument to get_tokenizer() to differentiate between preprocessing and other steps, so that during any step other than preprocessing it will just use the tokenizer found in the project directory.
I also added functionality to track the following stats: num segment lengths > 200, max segment length, and avg segment length. These will be helpful for tokenizer experiments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Fix issue where updated tokenizer not used during inference, add segment length stats to preprocess

---

silnlp/nmt/config.py
silnlp/nmt/open_nmt_config.py

I changed the method signatures in config.py and open_nmt_config.py for` _build_vocabs()` so that they would match the function signature in hugging_face_config.py. The function signature now reads as `def _build_vocabs(self, stats: bool=False) -> None:`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/195)

make method signature consistent for _build_vocabs()

---

silnlp/alignment/config.py
silnlp/common/packages_utils.py

I followed machine.py's methodology with a file containing functions that check if packages are available. I created a function to check if eflomal is available, and that function is called before importing eflomal.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/206)

Check eflomal exists before importing

---

Dockerfile
README.md

- Switched to installing SILNLP source code because using the binaries was causing the scripts to fail. 
- Removed the AWS CLI from the image because it's not practical to access the S3 bucket from inside the container.
- Clarified some of the documentation and added instructions for using ClearML/AWS credentials
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/217)

Use silnlp source rather than binary and update documentation

---

silnlp/common/environment.py
silnlp/common/extract_corpora.py

The extract_corpus script was failing when trying to access paratext projects from the S3 bucket because it expected the bucket to be mounted. I added support for copying paratext projects from the S3 bucket to the cache.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/223)

add support for copying paratext projects from S3 bucket

---

silnlp/common/translate_google.py
silnlp/nmt/translate.py

Added `copy_pt_project_from_bucket()` to scripts that needed to download pt projects to cache, namely translate.py and translate_google.py. I also added `copy_experiment_from_bucket()` and `copy_experiment_to_bucket()` to translate_google.py since it was missing those.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/227)

Download paratext projects from S3 bucket to cache

---

silnlp/common/extract_corpora.py
silnlp/common/paratext.py

I added some functions in paratext.py to determine versification in a paratext project. The functions allow for providing warnings to the user if there is an issue with the detected versification (i.e. unknown versification, different versifications for OT and NT) or if the detected versification doesn't match the project versification setting. I also added a call to the new `check_versification()` function in extract_corpora.py.
I tested this on an OTNT project, an only OT project, an only NT project, a project where the OT and NT had different versifications, a project where the detected versification doesn't match the project versification setting, and a project that didn't have enough book files to determine a versification,
- - -
This change is [<img …

add functionality for detecting versification when extracting corpora

---

silnlp/common/paratext.py

If a paratext versification setting is not included in the Settings.xml file for a project, the `check_versification()` function should assume the project is using the English versification (versification 4), since that is the default versification setting for paratext projects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/257)

change default versification to English (versification 4)

---

silnlp/nmt/translate.py

When running translate.py, a source project sub folder is now created, resulting in a directory structure of `project_dir/infer/steps/source_project/`. Also fixed a minor style warning.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/263)

create source project sub folder when translating

---

silnlp/common/translator.py
silnlp/sfm/style.py
silnlp/sfm/usfm.py

This change adds the parameter `ignore_occurs_under` to `update_sheet()` in style.py, with the default set to `False`. When set to `True`, `update_sheet()` ignores `OccursUnder` in custom stylesheets to prevent any parsing issues in `collect_segments_from_paragraph()`.  I set the option to `True` in every place where it is called when translating a book, and it is now handling the `\b` markers correctly in NIV84.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/269)

ignore OccursUnder in custom stylesheets when parsing book usfm

---

silnlp/nmt/hugging_face_config.py

With multiple custom tags, space tokens are inserted between each one (e.g. "\<first\> _ \<second\> _ \<third\>"). Is that ok?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/270)

Add special tokens for custom tags

---

silnlp/nmt/clearml_connection.py

This might be a design choice, and if it is, feel free to shoot this idea down (or at least this re-implementation of the logic), but it would be very helpful in the case of clowder (and I imagine other places as well) to be able to have an experiment more than 2 directories deep.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/275)

Change SILClearML contructor logic to allow for deeper directories

---

poetry.lock
pyproject.toml
silnlp/nmt/hugging_face_config.py

Whenever models are loaded from huggingface, they are now converted to BetterTransformer. SILSeq2SeqTrainer now overrides the Seq2SeqTrainer `_save()` function so that the models are reverted from BetterTransformer before saving as required. Also, pytorch has been upgraded from 1.10.1 to the most recent version of pytorch, 2.1.1, since BetterTransformer requires pytorch >= 2.0.0.
Results for three different experiments show a marked improvement when using BetterTransformers. The GPU memory utilization percent differences show improvements of 11.92% and 9.59%, with the third experiment's results not being able to be fully quantified since the baseline (NLLB 1.3B, batch size 16) ran out of memory while the BetterTransformers version ran successfully with a GPU utilization of 93.30%. The …

#264 bettertransformer

---

silnlp/nmt/clearml_connection.py
silnlp/nmt/experiment.py
silnlp/nmt/translate.py

Added `--commit` command-line argument to specify the commit with which to run the job on ClearML. This is particularly useful for clowder (i.e., can compare jobs across commits).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/281)

Add commit arg

---

silnlp/common/translator.py
silnlp/nmt/translate.py

There are a few individual projects that need to handle custom stylesheets differently. In #269, the change was made to ignore the OccursUnder and TextProperties fields by default to handle a parsing issue with the NIV84. With the ONAV, the updates to these fields need to be merged for correct parsing. This adds a command line argument to choose how to handle these fields, with merging being the default as it was previously.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/282)

Add argument in translate script for how to handle custom stylesheets

---

poetry.lock
pyproject.toml
silnlp/nmt/hugging_face_config.py

BetterTransformer is now configurable rather than always active. The reason for the change is that BetterTransformer doesn't support attention masks for padding, which we use in our experiments during batched training. There is now a `bettertransformer` boolean option under the `train` and `infer` sections of the config.yml for experiments. The default value is set to false.
I also upgraded the transformers package to the most recent version, 4.36.2, since as of version 4.36.0, Scaled Dot Product Attention (SDPA) is now part of transformers directly without needing to convert to BetterTransformer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/283)

make bettertransformer optional, upgrade to latest version of transformers

---

poetry.lock
pyproject.toml

Upgrading pytorch to 2.1.2 to fix an issue where a dependency on triton was included that was not compatible with Windows.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/291)

upgrade to pytorch 2.1.2

---

silnlp/nmt/hugging_face_config.py

When running the tests on their own, memory usage was ~10% with `torch_dtype=torch.float16` vs ~25% without for all 4 experiments. Additionally, inferencing was around 20 seconds faster for each 8-10 minute test. The BLEU scores were unchanged, though I was still seeing the weird 5 point bump in score for the one experiment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/304)

Force 16-bit inference when using mixed precision

---

silnlp/nmt/config.py
silnlp/nmt/hugging_face_config.py

With this PR, the following statistics for the source and target are calculated and saved to a csv file and excel file automatically during preprocessing without needing to use `--stats`: number of tokens added to vocab; min, max, median, mean, and stdev for tokens/verse, characters/verse, characters/tokens, words/verse, and characters/word; and number of verses >= 200 tokens (falls under tokens/verse section of spreadsheet).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/312)

Preprocess stats

---

silnlp/nmt/config.py
silnlp/nmt/hugging_face_config.py

No tokenization_stats file was being created when the tokenizer was not set to be updated in the config, causing the later _calculate_tokenization_stats() to fail since it depended on that file existing. I've adjusted the code so that it always creates the file and saves the statistics for added tokens in _build_vocabs() even if the tokenizer is not set to be updated. I've also added a check in _calculate_tokenization_stats() to make sure the file exists first, and if not to use a default dataframe containing just the column with the labels "source" and "target".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/315)

always create tokenization_stats files in _build_vocabs();_calculate_tokenization_stats() should work even if no stats file exists

---

silnlp/common/paratext.py

In warning messages where the OT and NT detected versifications conflict, or where the project versification setting conflicts with the detected versification, the warning message will now also include the key verses used to determine the detected versification so that the user understands how the determination was made.
Example warning message: `The detected OT versification 4 and the detected NT versification(s) 5, 6 do not match. The detected versifications were based on Daniel 3:30, Romans 16:24 being the last verse of their respective chapters.`
*Note, I chose to leave the versification in its numerical form rather than using its name because the paratext project's Settings.xml uses the numerical form.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …

update versification detection warnings to include key verses for detected versification

---

silnlp/nmt/hugging_face_config.py

`add_special_tokens` will not add a token if that token is already in the special tokens, and since the default behavior is to replace the whole special tokens list with the new list, passing the current list of special tokens effectively cancels them out, leaving only the most recent token. This was fine before because only one new language code is typically added for NLLB experiments, but for MADLAD, language codes are not special tokens by default and so adding both the source and target language causes the issue.
I'm actually going to stop adding the source language token for MADLAD because it isn't used, but the fix is still needed for any time >1 new language code is added.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Fix bug when adding multiple language codes

---

silnlp/nmt/hugging_face_config.py

This isn't necessarily the best learning rate for all T5 models, but the documentation that suggested a higher learning rate would be better was talking about T5 models in general.
For the experiment I was testing with, increasing the learning rate resulted in a BLEU score bump of 8 (+14.6%) in 3k less steps/2 hours less.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/336)

Add default learning rate for T5 models

---

silnlp/nmt/diff_predictions.py
silnlp/nmt/experiment.py
silnlp/nmt/hugging_face_config.py
silnlp/nmt/test.py

The names of the new scorers are `chrf3+` and `chrf3++`. I also copied over the `--scorers` option to `experiment.py` from the test script, but unlike the test script, the standard set of scorers will always be used and any additional scorers specified like `chrf3++` will be added.
`chrf3`, `chrf3+`, and `chrf3++` can be passed as values of `metric_for_best_model` in the eval section of a config to be used as the eval/early stopping metric. Investigation may need to be done to find the best `min_improvement` values for each.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/351)

Implement chrF3+ and chrF3++ as scorers and early stopping metrics

---

silnlp/common/translator.py
silnlp/sfm/__init__.py

Fixes issues with not being able to insert translations into books with SFM structure but no text.
Correct formatting of empty books with multiple verse markers on a single line.
Insert empty strings as text for empty target verses so that they're recognized by `collect_segments`.
No longer get rid of target project inline elements. I think the intention of this was to not bring over irrelevant information from source projects, so I don't think it needs to be applied to target projects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/357)

Fix target project parsing issues in translator.py

---

silnlp/nmt/hugging_face_config.py
silnlp/nmt/test.py

Previously the warning was given for testing but not translation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/364)

Give warning when base model is used for inferencing

---

silnlp/nmt/hugging_face_config.py

I was having trouble tying the embeddings to the lm_head in LoRA models where the embeddings were actually targeted layers, not just unfrozen, because the embeddings become a specific `lora_embedding` module, whereas the lm_head is treated normally, and the two aren't quite compatible. I didn't spend a ton of time on it because I know we mostly want to fully train the embeddings, so if we ever want to target the embeddings and keep them tied together, there is some more work to be done.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/372)

Lora weight tying update

---

Dockerfile

Removing the .NET SDK install steps got rid of an `apt-get update` command that I believe is necessary because of the `apt-get clean` command run after the main batch of packages is installed.
I'm still not sure what the issues were with failing to download python packages, but since those would come up before this issue, I'm going to assume there were some connectivity issues on Github's end
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/381)

Add apt-get update command after apt-get clean

---

silnlp/nmt/hugging_face_config.py

Per the discussion in issue #387, I'm setting use_reentrant to True by default to fix the warning, since it seems to perform slightly better than the False setting and is also the setting that we have been using, just not explicitly. If we run into any issues with freezing layers, the default can be overridden in the experiment's config.yml. When this pull request is approved, I'll go ahead and update the wiki with that info for the config.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/403)

set use_reentrant to true

---

silnlp/nmt/hugging_face_config.py

Changing the conditional rather than the actual learning rate because I found that to be the best learning rate for NLLB models using LoRA as well. I will have to do another set of experiments once we start testing MADLAD without LoRA to see if it needs a different learning rate.
After running these experiments, it seems like the slowdown from using LoRA is a mix of taking more steps and taking longer to complete a step. With the new learning rate, experiments are completing in a similar amount of steps compared to the original models, whereas before they took about twice as many steps to hit early stopping. Now, the training time for LoRA experiments is closer to 1.5 times that of regular experiments for Catapult, and 1.25 times for Scripture, which makes sense given that they previously …

Change default learning rate for LoRA models

---

README.md

When using a local GPU with Docker, you need to install the NVIDIA Container Toolkit and configure Docker to use the NVIDIA Container Runtime. I've added instructions for this to the readme.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/409)

update readme for installing nvidia-ctk and configuring Docker

---

Dockerfile
poetry.lock
pyproject.toml
silnlp/alignment/config.py

This PR updates eflomal from 0.1 to 2.0.0 to fix #431, modifies the Dockerfile to use the pip installation of eflomal, and adds eflomal to the `ALIGNERS` dictionary in `silnlp/alignment/config.py` permanently instead of only when eflomal is installed so that the error message will be `eflomal is not installed` rather than `invalid aligner`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/433)

Upgrade eflomal

---

silnlp/nmt/translate.py

This is so failure is correctly reported on ClearML.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/450)

Raise errors when source or target project isn't found for translation

---

silnlp/nmt/clearml_connection.py

This removes the warnings described in issue #316 when running an experiment remotely through clearml. I removed the ``-v /home/clearml/.clearml/hf-cache:/root/.cache/huggingface` docker argument since it's already present in the clearml.conf files on the servers we use, and I think it makes more sense to be in clearml.conf rather than clearml_connection.py.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/421)

disable tokenizer parallelism on remote jobs via env variable

---

.devcontainer/Dockerfile
silnlp/alignment/eflomal.py
silnlp/alignment/utils.py

Changes to allow non-MachineAligner aligners and aligners without an inverse model.
Also adds dependency and environment variable to use eflomal in the dev container.
Closes #443.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/455)

Generalize compute_alignment_scores

---

silnlp/nmt/experiment.py
silnlp/nmt/preprocess.py

New alignments weren't getting copied to the S3 bucket when using the force_align option because the files would already exist in the experiment folder. We wouldn't typically expect large files like a saved model to be in the experiment folder at this point, but I can update the code to only overwrite for the alignment files if necessary.
Plus a bunch of auto formatting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/453)

Overwrite alignment files when realignment occurs

---

silnlp/nmt/hugging_face_config.py

The only changed code that should be run before the first `_save` call is the `create_tied_embedding_weights` function, which got moved outside of the `HuggingFaceNMTModel` class, and when that function is called, now after the `lora_config` is loaded, and I did verify that the model was set up the same way it was before, i.e. that all the right weights were tied in the right ways. Previously, the losses, eval BLEU scores, and test scores were identical between reruns of the same experiment, so I'm not sure what could be causing this additional non-determinism.
<br>
A couple other pieces of information I didn't mention earlier that may or may not be useful:
* Most of the (identically configured) experiments I ran with these changes had the same best/last checkpoints (7k/11k), but a couple …

Save LoRA models as full merged models rather than adapters

---

silnlp/nmt/experiment.py
silnlp/nmt/translate.py

This fixes the issue in #464 by only matching with the checkpoint folder name rather than the whole path, so that there are no potential issues with characters in the experiment name that could interfere with regex matching. I also modified experiment.py so that it doesn't copy over all the contents in the experiment folder when the translate option is used. It now just downloads .yml files so that the program will have access to the configs, and any other downloads will occur when the program execution gets to _init_translation_task() in translate.py.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/465)

only match with checkpoint folder name not full path

---

silnlp/nmt/hugging_face_config.py

Adds option to find and use the highest batch size with the corresponding number of gradient accumulation steps. 
The new code mostly mirrors `accelerate` and the base Trainer's implementation of the `auto_find_batch_size` option, but adjusting the number of gradient accumulation steps needs to happen at the same time as adjusting the batch size as far as I can tell, so I wasn't able to just use the `auto_find_batch_size` option and adjust the grad. acc. steps after the fact.
Closes #371
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/424)

Auto gradient accumulation

---

silnlp/nmt/config.py
silnlp/nmt/hugging_face_config.py

Adds an optional field called `back_translations` to corpus pairs whose value is a list of projects in the same format as `src` or `trg`. Projects in this list have "_BT" appended to their language code so that their test set is evaluated separately. The new language code is still mapped to the correct NLLB language code.
Closes #377.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/451)

Add ability to specify projects as back translations

---

.devcontainer/Dockerfile
README.md
manual_setup.md
s3_bucket_setup.md
scripts/clean_s3.py
scripts/clearml_agent/clearml.conf
scripts/rclone/mount_to_s.bat
scripts/rclone/rclone.conf
silnlp/common/environment.py

This PR moves SILNLP from the aqua-ml-data S3 bucket to the new silnlp S3 bucket to address issue #468. I've tested that experiments are able to be successfully run with the new bucket.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/471)

migrate to new silnlp bucket

---

onboarding-dashboard/pages/InvestigationDetails.py

Fix #458 - cache should already be being invalidated in the streamlit app for most steps, but it was missing for the drafting step
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/469)

Onboarding dashboard clear draft cache

---

silnlp/xri/xri_etl.py

Implements just the loading of a tsv file into internal models.
Addresses https://github.com/sillsdev/silnlp/issues/473
Damien asked to have the work chunked up into smaller PR's so I have left the logic for creating the extract files not implemented currently.
---
If you want to play with it, here is some data you can test with:
```
id	source	target	split
0	Wakati wa kupanda, watu waligundua ingine dhaifu mlimani, ikiwa imejeruhiwa na kuachwa.	Enkagha yekebhusuro ,abhanto bhamanyire, obhurosu bhamorukereghe ,urabhone bhaikarwiri nokoghetigha.	train
1	Nyaraka za kale za ufafanuzi zilitumiwa mapema alfajiri.	!	train
2	Lengo lake lilikuwa wazi, lakini safari yake ilikatishwa ghafla wakati mgeni alipompa sadaka iliyowakilisha kila kitu alichokuwa akitafuta.	Obhusemi bhooche bhware harabhu, …
```

Add initial load functionality for xri_etl script

---

silnlp/nmt/config.py

It seems like the issue was coming from how the dataset was being copied/passed around when it goes through `split_parallel_corpus` followed by `filter_parallel_corpus`. I couldn't figure out exactly which operations were triggering the warnings, but setting the dataset explicitly instead of using `inplace` after all of the problematic bits took care of it, and I double checked that nothing was actually changing about the data.
Fixes #484.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/486)

Get rid of SettingWithCopyWarning

---

silnlp/nmt/hugging_face_config.py

This was preventing training when there was no val set.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/489)

Add check for metric name to handle the None case

---

silnlp/nmt/config.py
silnlp/smt/preprocess.py

This addresses issue #454.  It logs a warning if there are no test vrefs in the directory specified by the "use_test_from_from" parameter.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/485)

#454 "use_test_set_from" warning

---

silnlp/common/check_books.py

Check books provides a quick way to verify that the books in a Paratext project are parsed correctly. If they fail to parse the error message in VScode makes it easy to open the SFM file at the line that doesn't parse for a quick fix.
Complete Testaments aren't printed in full but as OT, NT or DT.
Replace print with logging statements.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/500)

Updates to check_books.py

---

silnlp/nmt/config.py
silnlp/nmt/hugging_face_config.py
silnlp/nmt/open_nmt_config.py

-Key Terms are no longer collected per corpus pair, done once for the whole corpus
-Any remaining duplicates are removed (repeated proper names)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/503)

Issue 333: Fixed bug with dupe key terms during preprocessing

---

silnlp/common/iso_info.py

Removed fre which isn't a code for french.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/509)

Remove spurious iso code for French

---

silnlp/common/compare_translations.py

- Created the compare_translations.py script and added it to silnlp/common
- The script takes 2 required arguments and 1 optional
- dir-path - the path to the directory where the translations are found and where the comparison output will be stored
- file-paths - the paths to each of the translation outputs that need to be compared, takes exactly 2 file paths
- scorers - optional argument that contains the set of scorers to use for comparison, default is:
{"bleu", "chrf3", "chrf3+", "chrf3++", "spbleu", "wer", "ter"}
- The output of this script is stored in comparison_scores.txt at dir-path and contains the relevant filenames and each scorer and result used.
I did not add an S3 bucket connection yet, but this script can be extended later on to add that functionality if needed.
- - -
This …

Issue 508: compare translations script

---

silnlp/common/extract_xri.py

This PR addresses 2 of the points raised in the code review feedback from Damien from this comment:
https://github.com/sillsdev/silnlp/pull/491#pullrequestreview-2261754354
- change the invocation method to run the script as a module
- move the file into `silnlp/common`
- rename the file to `extract_xri.py` to follow existing naming conventions
I will address the other point about output location in a follow up PR to make review easier. (I didn't want to rename a file and also change the code, but it looks like github's diff view actually does a good job of teasing those things apart)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/506)

Issue 473: change xri script to run as a module and rename

---

silnlp/common/corpus.py

TL;DR: A project with non-standard USFM was causing `get_scripture_parallel_corpus` to try to create illegal vref ranges. I don't think this particular scenario could happen with normal USFM, but the change won't affect standard use at all.
This error came about from a project with very non-standard USFM (the files are `.PTW`, but if that is another standard, I can't imagine that these files followed that either). In the files I looked at, there were lots of missing verse markers, chapter markers, etc.. This resulted in an extracted corpus with lots of `<range>` markers. In one case, a whole book was entirely `<range>` markers, so `get_scripture_parallel_corpus` was trying to create invalid cross-book VerseRef ranges, and it only got caught when the chapter number looped back around to …

Handle edge case caused by non-standard USFM

---

silnlp/common/extract_xri.py

This PR addresses one point raised in the code review feedback from Damien from this comment:
https://github.com/sillsdev/silnlp/pull/491#pullrequestreview-2261754354
> I would make the output directory an optional command-line argument. By default, you should extract files to `SIL_NLP_ENV.mt_corpora_dir`. This should point to the MT/corpora folder in the S3 bucket, which is where we would store this kind of corpus.
I wasn't clear on the directory structure to use within the corpora dir, so I kept the existing logic of generating a unique folder based on the cli inputs + timestamp.
Note that this PR is built off the back of https://github.com/sillsdev/silnlp/pull/506. When that one is merged I'll rebase this one and have it target `master`.
Once this PR is merged, all code review comments …

Issue 473: change how output directory is generated for extract_xri script

---

silnlp/common/extract_xri.py

This PR adds optional logging to the script.
Currently the script makes certain assumptions about the data which can make it a bit brittle causing it to crash mid-processing.
Some example assumptions:
- all columns exist with the expected schema
- no embedded newlines (e.g. each row is on one line)
- id's can all be parsed to `int`
Logging will help to quickly identify the row of data breaking it.
Currently the logging is off by default. Enabling with `-log [PATH]` sends the logs to the file specified.
Note this PR is built on top of another unmerged PR #473. I'll rebase this and target master when #473 is merged.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/514)

Issue 473 Add optional debug/info logging to extract_xri script

---

silnlp/common/extract_xri.py

This PR relates to Michael's request on issue https://github.com/sillsdev/silnlp/issues/494 for split lines:
> Filtering or correcting split sentences
> - Discard sentence pairs that don't follow the expected format
> - Stretch goal would be to re-assemble and retain sentence pairs that are split over 2 lines because of an embedded newline
The PR addresses the stretch goal part in that it repairs split lines, for example if the input tsv was this mess:
```tsv
id	source	target	split
0	source0	tar
get0	train
1	sour
ce1	tar
ge
t1	train
2	source2	target2	train
```
then it will process it as if it was this tsv:
```
id	source	target	split
0	source0	target0	train
1	source1	target1	train
2	source2	target2	train
```
The first request about discarding records that can't be processed hasn't been …

Issue 494: Add repair logic for split lines to extract_xri script

---

silnlp/common/extract_xri.py

This PR implemented some requirements from this comment https://github.com/sillsdev/silnlp/issues/494#issuecomment-2345328525:
- Discard sentence pairs that don't follow the expected format
- Removal of Missing translations (indicated by `!`)
- Removal of leading/trailing whitespace on the sentence pairs
This is implemented with a big imperative loop that iterates over the original rows and on each iteration of the loop it will `continue` if it hits anything it wants to filter out. At the end of the iteration it adds the cleaned up sentence pair into its return list.
Once this is merged, the only outstanding data cleaning requirement for the extract_xri script will be dealing with duplicate source sentences.
I also added some additional tweaks related to the split cell:
- Split is case …

Issue 494: Add basic filtering and cleaning to extract_xri script

---

silnlp/common/extract_xri.py

This PR adds duplication detection and deduplication logic to the script motivated by this requirement from comment https://github.com/sillsdev/silnlp/issues/494#issuecomment-2345328525:
- Duplicate LWC entries
- Log instances at error level
Duplicate entries are identified and logged at error level and the script removes duplicates, choosing the match that has target sentence closest in length to the source sentence.
---
Example tsv:
```
id	source	target	split
0	duplicate-source1	duplicate-target-1  	brain
2	duplicate-source1	!	dev
3	duplicate-source2	short-1  	brain
1	duplicate-source1	duplicate-target-2	dev
4	duplicate-source2	duplicate-target-2	dev
5	duplicate-source3	duplicate-target-2	dev
6	Duplicate-source3	duplicate-target-2	dev
```
Note that there's two pairs of duplicates:
- …

Issue 494: Add deduplication logic to extract_xri script

---

poetry.lock
pyproject.toml

clearml-session uses jupyter-server 2.14.2, which has a dependency on packaging>=22.0. This was preventing some other pip packages from being installed, in my case poetry and protobuf.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/529)

Upgrade 'packaging' to be compatible with the latest version of clearml-session

---

silnlp/nmt/config.py

-Added support for Spanish glosses
-Added an option to use one of the supported glosses (en, fr, id, es) even when the source language is not one of those four. -In the terms config, "include_glosses" can now be either true/false or one of the glosses language codes (en,fr,id,es) to indicate which gloss to use if the source is different.
NOTE: The wiki will need to be updated to reflect the "include_glosses" config change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/530)

Updated term glosses

---

silnlp/common/extract_xri.py

This PR addresses code review feedback here: https://github.com/sillsdev/silnlp/pull/517#pullrequestreview-2304183258
It converts the two optional cli arguments from single hyphen form (e.g. `-output`) to double hyphen form (e.g. `--output`) as per the project's style.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/526)

Issue 494: Change optional parameters in extract_xri to use double hyphens

---

silnlp/common/compare_translations.py

WER score is no longer used by the project team, and this allows compare_translations to only depend on sacrebleu and machine, instead of silnlp.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/534)

Removed WER score from compare_translations

---

silnlp/nmt/config.py

-In the config file, under the terms section, a new option was added: filter_books.
-filter_books uses the same syntax as corpus_books, except chapter selections will be ignored.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/531)

Added an option for a book filter for KBTs

---

silnlp/common/translate_google.py
silnlp/common/translator.py
silnlp/nmt/config.py
silnlp/nmt/experiment.py
silnlp/nmt/hugging_face_config.py
silnlp/nmt/open_nmt_config.py
silnlp/nmt/test.py
silnlp/nmt/translate.py

This adds the ability for SILNLP's translate functionality to produce multiple diverse drafts.  This ability is controlled by the --multiple-translations parameter on the command line (for both translate.py and experiment.py).  The other parameters, such as number of drafts and the method of creating multiple translations, are specified in the config file.
When multiple translations are requested, the output file name is given a different extension for each draft.  For example, if you specify "output.txt" as the output file and request 3 drafts, then three files will be created called "output.1.txt", "output.2.txt", and "output.3.txt".
The default method for producing multiple translations is called "hybrid" and uses a combination of beam search and sampling.  Other supported values are …

#513 multiple diverse drafts

---

silnlp/common/normalize_extracts.py

This PR adds an initial stubbed out script to normalize extract files.
It is the first step to implement the second half of this comment: https://github.com/sillsdev/silnlp/issues/494#issuecomment-2345328525
> # Normalization Script Responsibilities
>
> - Convert multiple consecutive spaces to a single space
> - Correct inconsistent spacing around punctuation
The main parts of the logic are stubbed out so when you run the script it doesn't do much:
```
$ python -m silnlp.common.normalize_extracts /tmp/xri --output hackery/normalized
2024-09-19 17:08:17,470 - silnlp.common.normalize_extracts - INFO - Starting script
2024-09-19 17:08:17,470 - silnlp.common.normalize_extracts - INFO - Output dir set to hackery/normalized
2024-09-19 17:08:17,470 - silnlp.common.normalize_extracts - INFO - …
```

Issue 494: Add stubbed normalization script

---

silnlp/common/extract_xri.py

This PR addresses Michael's feedback from this comment: https://github.com/sillsdev/silnlp/issues/546#issuecomment-2391314524 by switching the extract file to always use unix line endings (`\n`).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/548)

Issue 546: use unix line endings for extract files in all cases

---

silnlp/common/extract_xri.py

This PR addresses this feedback from Michael: https://github.com/sillsdev/silnlp/issues/546#issuecomment-2391335853
Any sentence pair where the source/target has only 1 character after trimming is filtered out.
---
Example input file:
```
id	source	target	split
0	s0 	 t0	train
1	s 	long	train
2	long	t	train
3	   s   	  t  	train
4	 source   	  !  	train
```
Only id=0 survives filtering as both source and target have 2 characters.
Example run showing just the cleaning logs:
```
python -m silnlp.common.extract_xri hackery/simple.tsv swa ngq hackery --output hackery/out --log-level DEBUG 2>&1 | grep clean
2024-10-03 23:17:03,148 - silnlp.common.extract_xri.clean - INFO - Starting filtering and cleaning stage
2024-10-03 23:17:03,148 - silnlp.common.extract_xri.clean - DEBUG - Required number …
```

Issue 546: Tighten filtering logic for single character sentences

---

silnlp/common/translator.py
silnlp/nmt/test.py

This PR addresses an issue that Isaac and Bethany found with empty verses in USFM.  I've also added the "--multiple-translations" option to test.py to match the behavior of experiment.py.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/552)

Fix for a bug with empty verses in USFM

---

scripts/clean_s3.py

This PR changes the default max months for the `clean_s3.py` script from 3 months to 1 month. It also adds a `--max-months` option to the script.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/555)

change default to 1 month, make max months an argument

---

silnlp/common/normalize_extracts.py

This PR fills in some of the blanks in the stubbed script created in https://github.com/sillsdev/silnlp/pull/527
The main parts:
- using a glob to narrow down the extracted files (if specified)
- ignoring files that aren't `.txt` or are already normalized
- loading extract files
- saving normalized extract files
Example usage:
```
$ python -m silnlp.common.normalize_extracts /tmp/extracted/ --output /tmp/normalized --log-level DEBUG
2024-10-05 22:09:16,264 - silnlp.common.normalize_extracts - INFO - Starting script
2024-10-05 22:09:16,264 - silnlp.common.normalize_extracts - INFO - Output dir set to /tmp/normalized
2024-10-05 22:09:16,264 - silnlp.common.normalize_extracts - DEBUG - Searching files in input dir: '/tmp/extracted'
2024-10-05 22:09:16,264 - silnlp.common.normalize_extracts - …
```

Issue 494: add file io for normalize script

---

silnlp/common/normalize_extracts.py

This PR adds very basic normalization for extract strings to shrink consecutive whitespace characters to a single space, e.g. `"a      b    \t\t     c"` -> `"a b c"`.
It addresses this requirement from Michael: (see https://github.com/sillsdev/silnlp/issues/494#issuecomment-2345328525):
> Convert multiple consecutive spaces to a single space
Note this goes a little further and will pick up _any_ whitespace (tabs, carriage returns, bells) and convert it to a regular space character. I haven't seen cases of this yet - just being cautious.
The only remaining requirement for issue 494 will be:
> Correct inconsistent spacing around punctuation
then issue 494 can be closed. Future requirements would go onto a different issue. I am waiting for a definition of what is considered "punctuation" …

Issue 494: Add normalization to shrink consecutive whitespace to a single space

---

silnlp/common/normalize_extracts.py

This PR is introduces the types and main happy path logic associated with normalizing punctuation.
See this comment for context: https://github.com/sillsdev/silnlp/issues/494#issuecomment-2404328574
The code is full of TODO's that will be addressed in subsequent PR's. It was getting too big for one PR...
Example:
```
Hello.,there my  friend ! How are you   ?
012345678901234567890123456789012345678901
0         1         2         3         4
Hello.,there my friend! How are you? 
```
It finds 4 candidates for normalization:
- `.,` at index 5 - this one has two punctuation characters so it leaves it alone
- double space at index 15 - this gets reduced to a single space
- exclamation point surrounded by whitespace at index 23 - this gets replaced with `"! "` effectively removing the leading …

Issue 494: Add normalization of punctuation

---

silnlp/common/check_books.py

Logging the full path to the SFM file is useful since there are some projects (e.g. NASB) with duplicate SFM files with different names.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/561)

Log the full path and file name of the parsed file.

---

silnlp/common/normalize_extracts.py
silnlp/common/normalize_tests.py
silnlp/common/normalizer.py

This PR adds warning functionality:
- the script outputs warnings
- more kinds of warnings are detected
I also did some refactoring to make adding warning code cleaner, so it's a big PR (sorry Damien!)
There's two kinds of warnings right now:
- consecutive punctuation characters (ignoring whitespace)
- (false negative) punctuation found in the sentences that doesn't have rules defined for it
Here is an example of some warning output:
```
7 warnings found
====================================================================================================
line: 1
0         1         2         3         4         5
012345678901234567890123456789012345678901234567890123456789
'Hi there - you! (my -    friend )  How's   it  going ?'
^^^
(14,17)
>>> WARNING_CODE: 0
>>> DESCRIPTION: Multiple …
```

(Issue 494): Enhance warning functionality

---

silnlp/nmt/clearml_connection.py

This PR replaces the old nvidia/cuda image in `clearml_connection.py` with the SILNLP docker image. There are additions to the `docker_setup_bash_script` to allow Poetry to use system-site-packages. It now only takes ~6 seconds instead of ~1 minute for all the packages to be installed when running an experiment.
You'll see that it currently specifies an exact version of the SILNLP docker container rather than using `latest`. This is because currently the ClearML agents are set to not pull new versions of docker images, so `latest` doesn't work. If we'd like the ClearML agents to always check for the latest version of the SILNLP image, I can update that in the `clearml.conf`. And then once all the agents are restarted I can update this code.
- - -
This change is [<img …

Use silnlp image, use system-site-packages

---

silnlp/common/paratext.py

This PR fixes #563 where, during the extract corpora process, the presence of a custom.vrs file would always cause the check_versification function to return a warning that the settings versification type does not match the detected versification type. Now, the function also checks whether the settings versification type is unknown, and if so, it compares the detected versification type against the settings *base* versification type and only raises a warning if those also don't match.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/569)

check base versification of custom versification before throwing warning

---

silnlp/common/environment.py

Due to the issue we were having with connections to the S3 bucket timing out, I've increase the read_timeout from its default setting of 60 seconds to 600 seconds, reason being it takes about 7 minutes to upload a 1.3B NLLB checkpoint. I've also changed the backoff from retrying 10 times with an interval of 5 seconds between attempts, to using an exponential backoff with 10 attempts where the interval ranges from 2^0 seconds to 2^9 seconds.
I tested this by queueing up 3 experiments at the same time, and they were all able to upload checkpoints without timing out. We'll still have to monitor experiments in the near future to verify that this has eliminated the issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

exponential backoff and increase read_timeout for S3 bucket

---

silnlp/common/normalize_tests.py
silnlp/common/normalizer.py

This PR adds more kinds of warning checks related to false positives where a punctuation character is potentially acting in ways not anticipated.
Example sentences:
```
It's Sam-the-main
His number is #4567 8884 216
She said ' hi'
```
Warnings:
```
2024-10-18 21:41:20,320 - silnlp.common.normalize_extracts - WARNING - 5 warnings found
2024-10-18 21:41:20,320 - silnlp.common.normalize_extracts - WARNING - ====================================================================================================
2024-10-18 21:41:20,320 - silnlp.common.normalize_extracts - WARNING - line: 1
2024-10-18 21:41:20,320 - silnlp.common.normalize_extracts - WARNING -             0         1
2024-10-18 21:41:20,320 - silnlp.common.normalize_extracts - WARNING -             01234567890123456789
2024-10-18 …
```

(Issue 494) Add false positive warnings and tests

---

silnlp/nmt/translate.py

I opted for this approach over only throwing an error or a warning because in the case of translation, we're not really looking for language codes from the test set specifically, though I do think it still makes sense to look for a test code first because they will almost definitely match the languages we want to translate between.
Closes #578
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/580)

Try to use a different iso code from the config when there is no test set

---

.devcontainer/devcontainer.json

This PR address #586 . It automatically runs poetry install after the devcontainer starts up, and it sets the default python interpreter to the python installed in the poetry environment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/587)

Automatically run poetry install and set python interpreter on devcontainer startup

---

silnlp/nmt/analyze_project_pairs.py

We'll have to go back and check to see if anything else is affected by no longer having a default model name ("SILTransformerBase"). I will create a separate issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/589)

Fix bug related to no model name

---

README.md

Adding the option to mount the S3 bucket as part of the conda setup instructions, since docker isn't part of the conda setup and therefore won't interfere with the rclone mount.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/596)

Update AWS instructions for conda setup in README.md

---

silnlp/nmt/hugging_face_config.py

This branch adds a wrapper around the NLLB tokenizer that runs the Moses punctuation normalizer before passing the text to the tokenizer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/617)

611 use punctuation normalizer in translate

---

silnlp/nmt/hugging_face_config.py

This PR adds support for splitting a model across two GPUs during training. There was already a num_devices argument in experiment.py that defaulted to 1, but it wasn't being used by any other part of the code, so I repurposed the argument. Now when the user specifies num_devices = 2 for an NLLB model, the model is loaded using the custom device map splitting it across two GPUs during the training phase.
I tested on 3 languages comparing 1 to 2 GPUs, and the BLEU scores were all within one point, with the 2 GPUs actually having a marginally higher BLEU score. These tests were conducted with the 40GB GPUs on the AQuA Server using the 1.3B NLLB model. I also started another set of 3 languages with the 2 GPU setup running on ORU, and although I confirmed that 2 24GB GPUs are now able to …

#285 multigpu

---

scripts/clean_s3.py

This PR addresses https://github.com/sillsdev/serval/issues/468. The clean_s3.py script now also cleans up serval data. Any file `pretranslate.src.json|pretranslate.tgt.json|train.src.txt|train.tgt.txt` in the folders `^(production|dev|int-qa|ext-qa)/builds/.+` that is older than 1 month will be deleted when this script is run. The script is run every week on Sunday at 1am CT as a cron job on the AQuA server.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/614)

clean serval data

---

silnlp/nmt/experiment.py
silnlp/nmt/hugging_face_config.py

Update the `hugging_face_config.py`:
- Load the model from the parent experiment if a parent is specified in the config. 
- The tokenizer will be the same as the parent experiment unless it is specified in the config.
- An optional parameter is added in `SilSeq2SeqTrainer` to store the model prefix (when the model is from a parent experiment, the model name will be a path, so we can't get directly a prefix).
This modification has been tested on:
The remaining potential issues:
- Model name becomes a path when the parent is specified, so it is not safe to directly use it anymore (such as in methods that need to get a prefix from the model name). That is why I edited the trainer class. I'm not sure if there are other methods that will be influenced, but I went over the related methods and …

Update for Issue #623 

---

silnlp/common/translator.py

In the DraftGroup constructor, the number of translations of the first sentence is used to determine the number of drafts created. When the first sentence was empty, it was interpreted as the output having no drafts, which caused the whole output to be ignored.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/633)

Fix format of empty sentences to remove DraftGroup num_drafts edge case

---

silnlp/nmt/hugging_face_config.py

I forgot to `get_mt_exp_dir()` before sending the parent path to the tokenizer :(
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/637)

Fix tokenizer bug when resumes from a parent experiment

---

silnlp/nmt/diff_predictions.py

`writer.save()` has been deprecated and replaced by `writer.close()`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/641)

Renew the deprecated method in diff_predictions.py

---

silnlp/common/environment.py

This PR addresses issue #640, where checkpoints have not been able to be uploaded to the S3 bucket. The root cause seems to be a network issue on our LC-WAN's end, and a person from the ILC IT Helpdesk has already submitted a ticket with them. However, setting `"addressing_style": "path"` in our s3 config seems to get around the issue, with 4/4 experiments successfully uploading checkpoints using that config setting, although I think a bit more slowly than normal. This changes the addressing from https://your-bucket-name.s3.amazonaws.com/object-key to https://s3.amazonaws.com/your-bucket-name/object-key, so potentially what's going on is that the LC-WAN is not correctly handling dynamically generated subdomains.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …

#640 ssl error

---

silnlp/nmt/hugging_face_config.py

The issue provides some background info about floating point formats and later might contain some notes from investigations, so I thought it would be useful to link to it from the code that sets the floating point precision.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/648)

Issue 647 - add link to floating point documentation

---

silnlp/common/compare_lex.py
silnlp/common/count_words.py

These two scripts run checks on XRI datasets. EITL team uses them regularly and I'd like to add them to silnlp.
- `count_words.py` prints total and unique word counts for the source and target datasets and gives stats on the diversity of target renderings for the most common source words. (May need a more precise name.)
- `compare_lex.py` compares lexicon data for two different source-target sets. It can be used to find what percent coverage each dataset has for the other, e.g. what percent of Bible words are represented in the training data. It defines "word" naively based on whitespace. Can be run on source side, target side, or both.
I've cleaned these up per a few helpful suggestions from Matthew: 
- lines < 120 chars
- uses SIL_NLP_ENV for paths to remain platform agnostic
- placed …

Add lexicon tools for use with XRI datasets

---

silnlp/nmt/analyze_project_pairs.py

When `analyze_project_pairs` was run on Windows and the experiment argument used backslashes, no calls to copy files to/from the S3 bucket were successful because the path was not normalized to only use forward slashes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/663)

Normalize experiment paths consistently

---

scripts/clean_s3.py

This addresses issue #671. The clean_s3.py script now first checks for the existence of keep_until files, which must be located in the same folder as an experiment's config.yml file and follow the format `keep_until_YYYY-MM-DD.lock' to take effect. The date is read from the filename and should be interpreted as the checkpoints losing protection from deletion at the beginning of that date. I've also added an Extra Info column to the output spreadsheet, where the protected until date for any protected files is added.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/672)

keep_until files for checkpoints

---

bucket_setup.md
silnlp/common/environment.py

- Note in bucket_setup for minimum rclone version needed
- use generate_s3_config whenever a s3 config is needed
This is a very small PR adding some things missed in this [PR](https://github.com/sillsdev/silnlp/pull/620)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/675)

Small updates missed in MinIO support added

---

silnlp/nmt/hugging_face_config.py

This PR addresses https://github.com/sillsdev/silnlp/issues/656.  It waits to wrap the tokenizer with the Moses punctuation normalizer until after the tokenizer has been fully initialized.  Previously, the source and target language codes were not being set appropriately on the tokenizer, leading to no language code being specified in the output.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/674)

Fix for #656 (mixed-language output)

---

silnlp/common/environment.py

There was an issue found with interactive sessions that caused them to never try to connect to an S3 bucket since `SIL_NLP_DATA_PATH=/silnlp` is included in the clearml.conf files and `BUCKET_SERVICE` is not set. There are three potential fixes to this issue:
1. Demote from an exception to warning when a local directory from `SIL_NLP_DATA_PATH` is not found.
2. Remove the environment variable `SIL_NLP_DATA_PATH` from each of the clearml agents. 
3. Add a different value for `BUCKET_SERVICE`, such as `any` to each of the clearml agents to force the use of an S3 bucket.
I chose this PR as the best option to not have to restart every agent, and this will allow `SIL_NL_DATA_PATH` to be set and tried first, with S3 as a fallback as long as `BUCKET_SERVICE=""` or is not set.
- - -
This change …

Fixed an issue with interactive sessions

---

silnlp/nmt/analyze_project_pairs.py
silnlp/nmt/clearml_connection.py
silnlp/nmt/translate.py

- Fixed an oversight with running translate and analyse_project_pairs not passing in bucket_service to SILClearML
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/680)

Made bucket_service required for SILClearML

---

.devcontainer/devcontainer.json
.devcontainer/update_hosts.sh

This PR addresses issue #679. I added a startup script `update_hosts.sh` to the .devcontainers folder, which will be run post startup and adds a necessary line to the /etc/hosts file to allow the SonicWall NetExtender VPN to work. The user will need to know the IP address for the MinIO bucket and use it to set the environment variable MINIO_ENDPOINT_IP in order for the script to add the line to the hosts file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/681)

Update hosts file in devcontainer

---

silnlp/nmt/analyze_project_pairs.py

This addresses issue #690. The `copy_experiment_to_bucket` call in the `get_corpus_stats` function in `analyze_project_pairs.py` now uses exp_name rather than exp_dir. I tested that `analyze_project_pairs.py` is now able to upload successfully when using a cache.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/691)

use exp_name rather than exp_dir for copy_experiment_to_bucket

---

silnlp/common/combine_scores.py

Fix a bug where the filenames were being created that included '/' characters.
Only prefix the output file names with the final folder name.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/683)

Add folder_name prefix to output files.

---

poetry.lock
pyproject.toml
silnlp/common/translator.py
silnlp/common/usfm_preservation.py
silnlp/nmt/experiment.py
silnlp/nmt/translate.py

* Added translation options to toggle placement of paragraph/style/embed markers
* Refactored to move all USFM marker-related work into UsfmPreserver and to always use UsfmPreserver for more consistency across possible configurations
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/694)

Revised translation options for USFM markers

---

silnlp/common/environment.py
silnlp/nmt/translate.py

This PR introduces the following improvements to the `silnlp/nmt/translate.py` command line arguments:
1. A new flag named `--data-dirs` was added that can be set to a list of absolute paths to any directories needed for translation
2. `--src` and `--trg` can now be absolute paths, or a relative path from any of the following directories: the ones listed in `--data-dirs`, `experiment` (not `MT/experiments`, but the experiment name folder), or `MT`. 
3. `--src-prefix`, `--trg-prefix`, `--start-seq`, and `--end-seq` will now check the `experiment` directory and any directories listed in `--data-dirs`
Results will always be stored in the `experiment` folder.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Translation script arguments relative to experiment directory

---

scripts/clean_s3.py
scripts/sync_minio_b2.py

This adds a script that will sync MinIO with B2 to be run with clean_s3.py periodically.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/692)

Sync minio b2

---

poetry.lock
pyproject.toml
silnlp/common/translator.py
silnlp/common/usfm_preservation.py

This is the implementation of marker placement pre- any related updates to machine.py, but keeping as many improvements made to this code since then. The only obvious way that output USFM will be different is that all of the paragraph markers for a verse will be present, even when they are not being placed, as it was before any marker placement-related updates.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/718)

Revert to older implementation of USFM marker placement

---

silnlp/common/environment.py
silnlp/common/translator.py
silnlp/nmt/diff_predictions.py
silnlp/nmt/experiment.py
silnlp/nmt/hugging_face_config.py
silnlp/nmt/test.py
silnlp/nmt/translate.py

This addresses issue #715. The `test.py` script now outputs a file called `test.trg-predictions.txt.[ckpt_num].confidences.tsv`. The file has two rows for each verse. The first row has the verse number and then each token, and the second row has the sequence confidence and then each individual token confidence, so that they are vertically paired with the first row. The `diff_predictions.py` script now has a couple new flags, `--chapter-score` which @AmeWenJ added that runs diff predictions at a chapter level rather than a verse level, and `--confidence` which adds a column to the dataframe for confidence scores.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/716)

Add confidence scores as output for test.py, diff_predictions.py, translate.py

---

silnlp/nmt/hugging_face_config.py

This small PR renames the `evaluation_strategy` config option to `eval_strategy` to fix a warning mentioned in [this issue](https://github.com/sillsdev/silnlp/issues/670).
This will also prevent errors whenever SILNLP is updated to another version of Transformers.
Here is the warning:
`evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead.
If we do not want this to break existing configs, we could map `evaluation_strategy` to `eval_strategy` to allow both names.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/741)

Replaced evaluation_strategy with eval_strategy

---

silnlp/common/onboard_project.py

This PR creates a new onboarding script that partially addresses https://github.com/sillsdev/silnlp/issues/732 and https://github.com/sillsdev/silnlp/issues/734.  It is able to copy a locally downloaded Paratext project to the appropriate location on the bucket.
This script should be able to house the additional onboarding functionality described in the other subtasks of https://github.com/sillsdev/silnlp/issues/732 (https://github.com/sillsdev/silnlp/issues/733, https://github.com/sillsdev/silnlp/issues/734, https://github.com/sillsdev/silnlp/issues/735, https://github.com/sillsdev/silnlp/issues/736, https://github.com/sillsdev/silnlp/issues/737, and https://github.com/sillsdev/silnlp/issues/738).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

New onboarding script

---

silnlp/common/postprocess_draft.py
silnlp/common/translator.py

Towards #746
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/750)

Add script for creating drafts with alternate postprocessing configurations

---

silnlp/common/extract_corpora.py
silnlp/common/onboard_project.py

This PR adds the following args to `onboard_project` and refactors `extract_corpora` to allow `onboard_project` to call `extract_corpora`:
- `--extract-corpora`
- `--include`
- `--exclude`
- `--markers`
- `--lemmas`
- `--project-vrefs`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/754)

Add extract_corpora to onboard_project

---

silnlp/common/compare_usfm_structure.py

Since the draft remark only gets added to the draft, the vrefs were not aligned between the two files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/757)

Ignore remarks and empty end-of-verse paragraphs

---

silnlp/nmt/diff_predictions.py

This patches a bug where a UnicodeDecodeError was occurring because the encoding was not specified when opening the file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/770)

add encoding to diff predictions when opening confidence file

---

poetry.lock
pyproject.toml
silnlp/common/translator.py
silnlp/nmt/postprocess.py

Closes #758
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/771)

Update draft remarks with machine

---

README.md
manual_setup.md

This PR removes old mentions of the silnlp cache from the README instructions, since the cache was removed entirely in this [PR](https://github.com/sillsdev/silnlp/pull/730).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/773)

Removed mentions of the cache from the README

---

silnlp/common/translator.py
silnlp/nmt/config.py
silnlp/nmt/diff_predictions.py
silnlp/nmt/experiment.py
silnlp/nmt/hugging_face_config.py
silnlp/nmt/test.py
silnlp/nmt/translate.py

This PR addresses #779, adding necessary features for the use of confidence metrics during the translation step. In particular, this adds the ability to generate chapter and book level confidence scores during translation, as well as a flag that enables all the confidence logic for test.py, translate.py, and experiment.py.
I tested with and without including the --save-confidences flag for test.py, translate.py, and experiment.py, ensuring that everything runs without error. I also tested that the confidence logic works for both .SFM and .txt files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/781)

#779 confidence

---

silnlp/nmt/test.py

Addresses issue #795 by adding confidence as a scorer for test.py (and by extension experiment.py) if the --save-confidences flag is present.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/796)

add confidence as scorer if --save-confidences is present

---

silnlp/nmt/hugging_face_config.py

This PR fixes issue #778, allowing the base NLLB model to translate with the correct language codes. 
`src_lang` and `trg_lang` are added as arguments for `_create_inference_model` and `_configure model` in `silnlp.nmt.hugging_face_config.py` to set the language codes properly in `_configure_model`. The test language codes are now used instead of the validation language codes, unless a different code is provided using the `--trg-iso` or `--src-iso` options for `silnlp.nmt.translate.py`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/788)

Fix bug with base NLLB translation

---

silnlp/nmt/quality_estimation.py

This module adds support for estimating the quality of drafts with regard to confidence, chrf3, and usability.
It requires a diff_predictions file to establish a correlation between confidence and chrF3, as well as confidence files to project chrF3 and ultimately usability from. The user has a few options to specify confidence files. They can provide a list of file paths (relative to the experiment directory) or they can specify just the book ids. They can also change the directory to look for confidence files in (relative to the experiment directory) e.g. /infer/5000/source. See the argument descriptions for more details. Also, if a usability_parameters.tsv file is present, it will use the parameters in that file for the chrf3 - usability distribution rather than the default parameters …

Add quality estimation module

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
README.md
backblaze_bucket_setup.sh
minio_bucket_setup.sh
rclone_setup.sh

This PR updates the README to include instructions on how to set up rclone with the standard Docker container. It also refactors the `minio_bucket_setup.sh` and `backblaze_bucket_setup.sh` files into one `rclone_setup.sh` script.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/803)

Update rclone setup for Docker

---

silnlp/nmt/experiment.py
silnlp/nmt/test.py

The previous PR only assumed to use the default model dir if train was not present during the translate step. This extends it to any step.
The value of `--save-checkpoints` is now only used if `--train` is present. Since no checkpoint is being made without train, experiment always assumes the default model dir.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/814)

Translate checkpoint issue

---

silnlp/nmt/experiment.py

A previous PR and merge had a misnamed variable in `experiment.py`, causing an error.  This PR corrects that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/817)

Fix misnamed variable `config` -> `translate_config`

---

silnlp/nmt/hugging_face_config.py

This fixes an issue where a unique out of memory exception on MIGs was causing our pipeline to error out. This PR creates a wrapper function for `should_reduce_batch_size` to add an extra check for the MIG out of memory exception. This can be removed if pytorch adds a fix to raise an expected out of memory exception, or if accelerate patches the `should_reduce_batch_size` method to support the current exception on MIGs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/819)

#756 mig gpu

---

silnlp/common/analyze.py
silnlp/common/postprocess_draft.py
silnlp/nmt/clearml_connection.py
silnlp/nmt/experiment.py
silnlp/nmt/translate.py

This PR adds the optional argument `--clearml-tag` to scripts that use ClearML to add a tag to Tasks that are run on ClearML. The possible options for `--clearml-tag` are: `research`, `dev`, `eitl`, and `onboarding`. Each of them will be appended with `silnlp-` once the Task is created to match the formatting of the SF tags.
I can make tags required or change the list of possible tags if needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/823)

Add tags to clearml tasks
