sillsdev/silnlp

- poetry.lock
- pyproject.toml
- silnlp/__init__.py
- silnlp/common/extract_corpora.py
- silnlp/common/filter_parallel.py
- silnlp/common/paratext.py
- silnlp/common/translate_google.py
- silnlp/common/translator.py
- silnlp/common/utils.py
- silnlp/nmt/analyze.py
- silnlp/nmt/average_checkpoints.py
- silnlp/nmt/config.py
- silnlp/nmt/export_embeddings.py
- silnlp/nmt/langs_config.py
- silnlp/nmt/preprocess.py
- silnlp/nmt/replace_embeddings.py
- silnlp/nmt/test.py
- silnlp/nmt/train.py
- silnlp/nmt/translate.py
- silnlp/smt/config.py
- silnlp/smt/preprocess.py
- silnlp/smt/test.py
- silnlp/smt/train.py
Small updates to extract_corpora, including starting some logging.
> Updates to extract_corpora

- README.md
- poetry.lock
- pyproject.toml
- silnlp/__init__.py
- silnlp/nmt/config.py
Just a few small changes based on requests.
> More small updates

- silnlp/assets/es-Major-glosses.txt
- silnlp/assets/fr-Major-glosses.txt
- silnlp/assets/id-Major-glosses.txt
- silnlp/common/corpus.py
- silnlp/common/paratext.py
- silnlp/common/utils.py
- silnlp/nmt/config.py
It should work but it is untested.
> #69 extract keyterms from multiple langs

- README.md
- poetry.lock
- pyproject.toml
- scripts/scratchpad_s3.py
- silnlp/common/environment.py
- silnlp/nmt/clearml_experiment.py
- silnlp/nmt/config.py
add capability to train a child model from a parent using clearml and S3 buckets.
> #79 clearml parent child

- silnlp/common/split_parallel.py
Fix split_parallel.py so that test and validation sets don't contain blank or identical lines.
> #137 Fix issue 

- silnlp/common/environment.py
Make it possible to change the location of extractions and Paratext files
> Extractions and Paratext directory from environment variable

- silnlp/alignment/machine_aligner.py
- silnlp/common/metrics.py
- silnlp/nmt/translate.py
The machine aligner returns alignment scores by updating the word_pairs parameter, rather than returning them from the method.
> Nmt alignment stats

- silnlp/smt/config.py
- silnlp/smt/preprocess.py
- silnlp/smt/test.py
- silnlp/smt/train.py
Fixed issue where SMT was not copying experiments to computer when setting SIL_NLP_DATA_PATH to /aqua-ml-data
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/162)
> Fix for SMT not copying experiments to computer

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- silnlp/nmt/preprocess.py
- silnlp/nmt/test.py
- silnlp/nmt/train.py
I created a .devcontainer folder with a devcontainer.json file and Dockerfile so that the SILNLP repo can be set up in a Docker container. Also fixed an issue where NMT preprocess, train, and test were not copying experiments from the S3 bucket when SIL_NLP_DATA_PATH is set to /aqua-ml-data.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/163)
> docker for silnlp; nmt copying experiments from bucket

- silnlp/nmt/hugging_face_config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/169)
> fix issue where ckpt was used instead of ckpt_path

- silnlp/nmt/config.py
- silnlp/nmt/hugging_face_config.py
- silnlp/nmt/tokenizer.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/197)
> don't tokenize and detokenize test.trg.detok.txt, only normalize

- .devcontainer/devcontainer.json
- silnlp/nmt/clearml_connection.py
- silnlp/nmt/config.py
- silnlp/nmt/diff_predictions.py
- silnlp/nmt/hugging_face_config.py
- silnlp/nmt/open_nmt_config.py
- silnlp/nmt/preprocess.py
- silnlp/nmt/segment_length.py
- silnlp/nmt/tokenizer.py
- silnlp/nmt/translate.py
I added some code to apply normalization before calculating missing characters and trained tokens.
For characters I simply pass the whole set of characters from the dataset into `normalize_target_all()` and strip out any whitespace, removing any resulting empty strings, before calculating missing characters.
For trained tokens, I created a new `normalize()` function inside of the `HuggingFaceTokenizer` class. I instantiate an instance of this class and use it to initialize a custom Normalizer, which I assign to the sentencepiece tokenizer that will be trained. After it trains, I change the sentencepiece tokenizer back to using a non-custom normalizer because the model can't save with a custom one, and that would be a problem since the saved json file is needed to access its merge rules.
I …
> Normalize before calculating missing characters and trained tokens

- poetry.lock
- pyproject.toml
- silnlp/nmt/__init__.py
- silnlp/nmt/clearml_connection.py
- silnlp/nmt/config.py
- silnlp/nmt/hugging_face_config.py
- silnlp/nmt/tokenizer.py
- update to latest version of transformers
- cleanup tokenizer interface inconsistencies
- support experiments with no validation splits
- fix various typing errors
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/209)
> Fix insertion of lang codes for NLLB

- silnlp/sfm/usfm.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/211)
> Loosen footnote caller requirements to allow for more than one character

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/212)
> Add documentation for using docker image

- silnlp/common/translator.py
- silnlp/nmt/translate.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/213)
> Add option to not include footnotes in translation

- silnlp/common/translator.py
- silnlp/sfm/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/215)
> Empty verse newline bug

- README.md
Updated the readme to add information about all the environment variables that need to be set for an silnlp dev environment. Also added some links to the wiki.
Wiki changes:
Added pages "Alignment: Usage", "Installing External Libraries", and "Using the Python Debugger".
Added information to "Configure a model" page about the new syntax for specifying chapters and the most useful parameters to change to make models train quickly for development purposes.
Added instructions to "Install silnlp on Windows 10" for permanently setting environement variables.
Updated function documentation in "NMT: Usage".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/229)
> Update readme and wiki

- silnlp/common/translator.py
- silnlp/nmt/translate.py
Remove commented code.
Move the Logging message that indicates the sfm file parsed correctly after the collecting the book id, inline elements and segments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/242)
> Remove commented code

- scripts/clear_clearml_cache.py
The clear cache script is working now. I checked to make sure the corresponding folder contents were deleted on the AQuA server when the script is run.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/246)
> fix clear cache script

- silnlp/nmt/config.py
- silnlp/nmt/test.py
- silnlp/nmt/translate.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/254)
> Update get_chapters function calls

- poetry.lock
- pyproject.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/256)
> update sil-machine to 1.0.2

- silnlp/common/translate_google.py
- silnlp/common/translator.py
- silnlp/nmt/translate.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/260)
> Add remark in drafts of USFM files with info about the model

- poetry.lock
- pyproject.toml
- silnlp/common/paratext.py
- silnlp/nmt/test.py
- silnlp/smt/config.py
- silnlp/smt/test.py
- silnlp/smt/train.py
- fix various type issues
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/262)
> Update SMT pipeline to use Machine.py

- silnlp/common/corpus.py
- silnlp/common/paratext.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/274)
> Filter out '...' verses during preprocessing

- README.md
Added information on installing the NVIDIA drivers and added a version of the `docker create` command with `--gpus all` for those with local GPUs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/276)
> update readme for setting up environment with local GPU

- silnlp/nmt/experiment.py
- silnlp/nmt/hugging_face_config.py
- silnlp/nmt/test.py
Added ability to test a model without fine-tuning it.
If you run the test script by itself rather than via an experiment and you use the last/best/avg flags, you'll get an error, but I can change it to not fail and instead test the base model if that makes more sense.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/299)
> Test without training

- poetry.lock
- pyproject.toml
- silnlp/nmt/hugging_face_config.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/314)
> Add configurable support for LoRA

- silnlp/nmt/config.py
- silnlp/nmt/experiment.py
- silnlp/nmt/open_nmt_config.py
- Updated preprocessing alignment to not realign project pairs that were previously aligned
- Added --force-align option
- Added function to include all stats present in the experiment folder to corpus-stats.csv
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/322)
> Alignment Interruption Handling

- clowder/investigation.py
Added a check so that the investigations could be processed without a /.
At the moment this shouldn't be required, but if we were to ever separate out the Bleu scores from all the extra details it would be required.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/326)
> Slightly more robust syncing

- silnlp/nmt/config.py
- silnlp/nmt/preprocess.py
- Add default value for force_align in preprocess function so it works with clowder
- Add force_align option to preprocess script
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/328)
> Force Align Fix

- silnlp/common/environment.py
Necessary for https://github.com/sillsdev/silnlp/issues/310
I'll push all of the necessary clowder changes to main once this is merged.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/335)
> Provide ability to override silnlp pt dir, scripture dir, and terms dir via env vars

- silnlp/nmt/config.py
Also updated documentation.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/339)
> Change defaults for disjoint_val and disjoint_test to True

- silnlp/nmt/config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/341)
> Fix bug that prevented creating a test set with test_books when disjoint_test=True

- silnlp/nmt/config.py
Changed to use None when no model is specified rather than False
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/342)
> Change default value of src/trg_script_in_model

- silnlp/common/collect_verse_counts.py
Fixes https://github.com/sillsdev/silnlp/issues/353
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/354)
> Books field is now the number of non-empty books

- silnlp/nmt/hugging_face_config.py
Also added a clarifying comment and slight tweak to PEFT model loading after I stumbled upon the explanation for that line that I was looking for months ago :)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/356)
> Lowercase metric_for_best_model

- silnlp/nmt/hugging_face_config.py
Changed the behavior of _find_missing_characters() to go line by line through each file in the corpus, normalizing the line first before using it to update the set of all characters in the corpus.
All other changes in the PR are the result of autoformatting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/359)
> normalize lines before getting charset

- silnlp/common/script_utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/361)
> Handle empty strings passed to get_script

- scripts/clean_s3.py
Added a script to remove any model files that haven't been modified in over 3 months. I approximated a month in terms of the average number of seconds in a month to keep the calculation simple. It's not exact, but I figure it will do for our purposes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/369)
> add script to remove >3 month old model files

- clowder/investigation.py
- silnlp/nmt/experiment.py
- silnlp/nmt/test.py
Updated score files to have only one line for each data pair. There is a column for each metric whether it's used or not. I also updated the default scorers for the experiment script to include all the chrF scores and none of the error rate ones.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/363)
> Score file format cleanup

- clowder/investigation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/374)
> Clowder: properly update clearml id across multiple users

- silnlp/nmt/translate.py
List failed books in the error message. This doesn't prevent anything else from happening.
Closes #389
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/399)
> Raise error after all books are translated if any translation failed

- README.md
- manual_setup.md
- s3_bucket_setup.md
Adding some information to the README on how to set up silnlp for macOS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/401)
> Adding documentation for set up on macOS

- onboarding-dashboard/Home.py
- onboarding-dashboard/pages/LogIn.py
Fixes #407 
Attempts to fix #414
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/428)
> Onboarding dashboard resources load and auth

- onboarding-dashboard/Home.py
- onboarding-dashboard/pages/LogIn.py
Reverts sillsdev/silnlp#428
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/429)
> Revert "Onboarding dashboard resources load and auth"

- onboarding-dashboard/Home.py
- onboarding-dashboard/pages/InvestigationDetails.py
- onboarding-dashboard/pages/LogIn.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/430)
> Onboarding dashboard resources load / auth token refresh issue

- onboarding-dashboard/pages/InvestigationDetails.py
- onboarding-dashboard/pages/LogIn.py
Continue work on #414
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/434)
> Onboarding dashboard auth settings

- onboarding-dashboard/pages/InvestigationDetails.py
Addressing #413
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/432)
> Onboarding dashboard alignment target suggestion

- silnlp/alignment/config.py
- silnlp/alignment/eflomal.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/436)
> Move eflomal checks inside of eflomal.py

- onboarding-dashboard/Home.py
- onboarding-dashboard/pages/InvestigationDetails.py
#413
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/437)
> Onboarding dashboard aligmentn target suggest

- .gitignore
- onboarding-dashboard/Home.py
- onboarding-dashboard/pages/InvestigationDetails.py
- onboarding-dashboard/utils.py
Also, minor changes:
* Add locks to gitignore
* Remove unnecessary constant for resource list length Add typing to utils
* Use check* functions when creating new investigation for consistency
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/439)
> Implement success messages with st.success and toast for all non-page-changing forms

- silnlp/nmt/clearml_connection.py
Catch error before it happens and give a better error message.
Closes #405.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/452)
> Add more descriptive error message for empty config file

- onboarding-dashboard/Home.py
- onboarding-dashboard/pages/LogIn.py
Fix #411
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/461)
> Onboarding dashboard nested resource upload (in zips)

- silnlp/common/extract_flex.py
Added a script to extract FLEx xml to txt file extracts. Example usage `python -m silnlp.common.extract_flex "jarawara.flextext" --only-langs jaa pt`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/477)
> Extract script for FLEx projects

- clowder/environment.py
- onboarding-dashboard/pages/InvestigationDetails.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/479)
> Fix timezone / sync issues with remote meta

- clowder/environment.py
- clowder/investigation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/480)
> Allow clowder to function when SIL_NLP_DATA_PATH, SIL_NLP_CACHE_* vars aren't set

- silnlp/alignment/bulk_align.py
- silnlp/common/corpus.py
Closes #498.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/499)
> Fix bug in get_scripture_parallel_corpus and simplify code in align_set

- silnlp/common/extract_flex.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/501)
> Add text id filtering logic for flex data extraction

- silnlp/xri/xri_etl.py
This PR extends the work in https://github.com/sillsdev/silnlp/pull/491.
That PR added generation of `all.txt` files. This PR further adds generation of `(train/val/test).txt` files.
Note that currently there is no data transformation logic, that will be added in later PR's.
---
Note that this PR currently targets branch `issue-473-add-file-saving` and not `master` as I'm waiting for https://github.com/sillsdev/silnlp/pull/491 to be approved and merged, so I continued working targeting my first branch. When 491 gets merged I'll change this PR to target `master`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/493)
> Adding generation of (train/val/test).txt files to XRI etl script

- silnlp/nmt/config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/512)
> Fixed bug in for loop for target terms

- silnlp/common/paratext.py
- silnlp/common/script_utils.py
- silnlp/common/translator.py
Missed this in the parser change and also found a couple other spots where it may be helpful
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/523)
> Use utf-8-sig encoding when reading files

- environment.yml
This PR adds an environment.yml file so that conda can be used as another option besides docker. Once the PR is approved, I'll also update the wiki to document how to run SILNLP with conda and how to set up a clearml-agent using conda.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/524)
> add conda environment.yml for non-python-package dependencies

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/528)
> Update README.md with conda instructions

- silnlp/nmt/hugging_face_config.py
- silnlp/nmt/open_nmt_config.py
This changes the syntax in `hugging_face_config.py` and `open_nmt_config.py` so that the "with" statements are compatible with Python 3.8. I also fix a few minor syntax issues that I saw.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/539)
> keep with statement syntax compatible with python 3.8

- README.md
This PR updates the readme to differentiate between instructions for setting up a local GPU with WSL vs. Linux.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/556)
> update local GPU instructions for dev container

- silnlp/common/normalize_extracts.py
- silnlp/common/normalize_tests.py
- silnlp/common/normalizer.py
This PR adds a new file full of unit tests to lock down the current normalization spec and fix all the niggling edge cases.
The core normalization logic was getting too big so I moved the `Normalizer` class and a lot of the supporting functions and data classes into a new file `normalizer.py`. That makes it hard to see some of the logic changes unfortunately.
The original script `normalize_extracts.py` is now just responsible for script boilerplate that wraps around the normalizer, like handling cli input, loading files, writing files.
@bhartmoore The test file in this PR adds a lot of examples if you're interested.
When you run the script there is some debug visualization output to make it a bit easier to understand the transformations (see below example).
Here's an example run over …
> Issue 494: Add tests for normalization and fix many bugs

- silnlp/common/check_books.py
Closes #570
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/571)
> Account for formatting of book file names in check_books.py

- silnlp/nmt/analyze_project_pairs.py
I also changed when the experiment is downloaded from the bucket so that it isn't all downloaded locally when using ClearML.
Closes #573
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/575)
> Save files incrementally

- silnlp/nmt/hugging_face_config.py
- silnlp/nmt/translate.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/581)
> Expand support for step checkpoints

- silnlp/nmt/config.py
- silnlp/nmt/hugging_face_config.py
Solve Issue #365 and #390 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/584)
> Solve Issue #365 and #390

- silnlp/common/collect_verse_counts.py
- silnlp/nmt/analyze_project_pairs.py
Closes #601
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/603)
> Fix lines affected by pandas version update

- .devcontainer/Dockerfile
- Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/607)
> Fix typos in EFLOMAL_PATH declarations in Dockerfiles

- silnlp/common/paratext.py
- silnlp/common/translator.py
Closes #615
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/618)
> Allow get_iso to work for any Paratext project

- silnlp/nmt/hugging_face_config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/635)
> Fix mismatched names and defaults for attn_implementation

- silnlp/nmt/experiment.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/638)
> Add preserve_usfm_markers as possible option for translate_config.yml

- poetry.lock
- pyproject.toml
This PR closes #574 by updating to the latest version of sil-machine, which properly handles mismatched book ids.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/639)
> Handle mismatched book IDs

- silnlp/common/normalize_extracts.py
- silnlp/common/normalizer.py
This PR addresses most of the TODO's that have been accumulating in the normalization code added under issue 494: https://github.com/sillsdev/silnlp/issues/494
It also adds some more comments and documentation.
There's no significant logical changes, just some extra checks and better logging.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/597)
> Issue 494 - address TODO's and improve documentation

- silnlp/common/corpus.py
- silnlp/common/paratext.py
- silnlp/nmt/config.py
- silnlp/nmt/hugging_face_config.py
This PR fixes an issue where only English glosses are being pulled even when another gloss ISO is present in the source.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/636)
> Issue 630 - Fix Non-English glosses bug

- silnlp/nmt/config.py
- silnlp/nmt/hugging_face_config.py
- silnlp/nmt/test.py
-Added support for Multi-Target training and testing
-Made many_to_many mapping the default for corpus pairs to prevent crashes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/651)
> Multi Target Support

- silnlp/nmt/hugging_face_config.py
I found in the code that the early stopping callback automatically adds "eval_" to metric names if they don't already start with it, so both "loss" and "eval_loss" point to evaluation loss.
Closes #654
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/657)
> Add support for evaluation loss as an early stopping metric

- silnlp/alignment/preprocess.py
Hooray for modular code
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/658)
> Add ability to configure the books/chapters that get aligned

- silnlp/common/translator.py
- silnlp/common/usfm_preservation.py
* Make preserving embeds off by default, reusing --include-inline-elements option for now
* Handle empty verses/lines with only embeds better
* Update some variable names to be more accurate, clean up code for adding embeds to updater rows
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/662)
> USFM Preservation Updates

- silnlp/common/corpus.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/665)
> Fix Project-Specific KBT Issues

- silnlp/common/compare_translations.py
Changes:
* Skip empty verses
* Add flag to allow empty scoring
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/667)
> Skip empty verses when comparing drafts

- silnlp/nmt/config.py
- silnlp/nmt/hugging_face_config.py
- silnlp/nmt/test.py
This reverts commit a063c556c11d3580305d63d0ab160f69eafa80c9.
This PR temporarily removed multi-target support to resolve this [issue](https://github.com/sillsdev/silnlp/issues/669)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/673)
> Revert "Multi Target Support (#651)"

- silnlp/common/environment.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/677)
> Bucket service default to ""

- scripts/rclone/mount_minio_to_m.bat
- silnlp/common/environment.py
The certificate for MinIO's url was updated, so SSL verifcation can be enabled again. Tom wants this enabled for security.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/687)
> Readded SSL verifcation

- silnlp/nmt/translate.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/695)
> Fix optional patterns argument in _init_translation_task

- silnlp/nmt/analyze_project_pairs.py
Resolves inconsistent behavior between local and ClearML jobs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/701)
> Let ClearML class do path normalization

- backblaze_bucket_setup.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/710)
> Fix bug in backblaze_bucket_setup.sh

- silnlp/nmt/analyze_project_pairs.py
Closes #711
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/712)
> Always upload summary stats files

- silnlp/common/clean_projects.py
A new script for removing unnecessary data from project folders. 
Possibly this could be part of the solution to issue #725 
Other wise it is a script I can run occasionally manually. 
I don't think that it removes any data that we make use of, but it may well be removing data that we might possibly make use of in the future. I'm trying to err on the side of caution regarding the removal of PII from our shared project folders.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/729)
> Replace clean_projects with new script

- poetry.lock
- pyproject.toml
Variety of bug fixes from machine.py
closes #707
closes #744
closes #745
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/749)
> Update to sil-machine 1.7.2

- silnlp/common/postprocess_draft.py
I realized that Windows users won't be able to use this without running on ClearML because of eflomal, so unfortunately this script isn't as convenient for the EITL team as I had originally thought. Regardless, I think it will be useful in the future once eflomal  is usable outside of Linux and also more generally if/when we add more post-processing options.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/755)
> Add ability to run postprocessing with an experiment and with ClearML

- silnlp/nmt/hugging_face_config.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/763)
> Restore missing import

- silnlp/nmt/exp_summary.py
This script supports a more efficient way to create experiments results spreadsheet. The usage will be updated in the wiki page.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/798)
> Script for pulling experiments results into excel sheets as long as the experiments are structured in a certain format 

- silnlp/nmt/quality_estimation.py
This modifies `quality_estimation.py` to create a file called `usability_verses.tsv` that contains usability scores for each of the verses in the specified books.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/815)
> Add verse-level usability scores

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/silnlp/818)
> Updated README instructions for rclone_setup
